apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: "kube-nginx-proxy"
  labels:
    app: "kube-nginx-proxy"
    version: "0.4.5"
  namespace: "dev"
  annotations:
    description: "nginx reverse proxy for services and pods powered by annotations"
spec:
  template:
    metadata:
      labels:
        app: "kube-nginx-proxy"
    spec:
      hostNetwork: true
      # use a nodeSelector to control where pods are scheduled
      # e.g., specify a hostname to run on a single host, or a label to run on a specific group of hosts
      #nodeSelector:
      #  kubernetes.io/hostname: <host>
      #  <label_name>: <label_value>
      containers:
        - name: "kube-nginx-proxy"
          # I was able to publish to my DockerHub account, because I don't have password to neither `avinor` nor `avinorps` accounts`
          # This line means, that during Wildcard deployment exactly this version of package will be taken.
          # In future here should be either: `avinorps/kube-nginx-proxy:latest` or `avinor/kube-nginx-proxy:latest` or `ghcr.io/avinor=ps/kube-nginx-proxy:latest`
          image: "andriilundiak/kube-nginx-proxy:0.4.5"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
