on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request: {}
name: Build and Publish

env:
  TAG: ${{ github.ref_name }}
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags') }} # Another way to get event of Release (because github.event_name = 'push' and not 'release'). Seems to be GitHub Actions bug.
  USE_DOCKERHUB: false
  USE_GHCR: true
  testStr: "event_name: ${{ github.event_name }} | ref: ${{ github.ref }} | ref_name: ${{ github.ref_name }}"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo "${{ env.testStr }}"

      - name: "[Dockerhub] Docker login"
        if: ${{ env.USE_DOCKERHUB && env.IS_RELEASE == 'true' }}  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}  
      
      - name: "[GHCR] Docker login"
        if: ${{ env.USE_GHCR && env.IS_RELEASE == 'true' }} 
        uses: docker/login-action@v1
        with:
          registry: ghcr.io # docker.pkg.github.com
          username: ${{ github.actor }} # ${{ github.repository_owner }}
          password: ${{ github.token }} # ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        if: ${{ env.IS_RELEASE == 'true' }} 
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        if: ${{ env.IS_RELEASE == 'true' }} 
        uses: docker/build-push-action@v3
        with:
          context: .
          # platforms: linux/amd64,linux/arm64 # by default linux.amd64
          push: ${{ env.IS_RELEASE == 'true' }} 
          tags: | 
            ghcr.io/${{ github.repository_owner }}/kube-nginx-proxy:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/kube-nginx-proxy:latest

